### ISSUE TITLE
'message': 'User errors were found in at least one of the child runs.',

### ISSUE THREAD

**Issue by Maryam-Ah** [swatig007/automlForImages#25]
when I submit the experiment in the object detection model, I get this error:

Status
Failed
UserError: User errors were found in at least one of the child runs.
Sampling policy name
GRID
Parameter space
{"model_name":["choice",[["fasterrcnn_resnet50_fpn"]]]}

**Comment by raduk** [comment]
Hi Maryam-Ah,

There are multiple reasons for the runs to fail, from compute errors to data errors. You would need to navigate to the child runs that failed and see the specific error message. 


From the main run, click on "Child Runs":

![image](https://user-images.githubusercontent.com/3809388/121103160-1bd64500-c7b4-11eb-8b44-c05e4dd02fd8.png)

Then again navigate to the child runs of the run, and in the bottom of the screen you'll see the list of the training runs:

![image](https://user-images.githubusercontent.com/3809388/121103287-7b345500-c7b4-11eb-9317-1e4b0820e8f9.png)

If you click on any of those, you can navigate to the logs and see the exact issue that caused the run failure:

![image](https://user-images.githubusercontent.com/3809388/121103520-fac22400-c7b4-11eb-88ee-1655910de801.png)

Please let me know once you identified the issue.

Thanks,
Radu

**Comment by raduk** [comment]
Closing as there is no follow-up on this
